PREFIX ?= /usr/local
BINDIR  = $(PREFIX)/bin
DATADIR = $(PREFIX)/share/gallery_generator

ASSETS = index.php image_detail.php download.php download_images.php styles.css
ENV_FILE = $(HOME)/.gallery_generator.env

.PHONY: install uninstall deps setup

install:
	@echo "Installing gallery_generator..."
	install -d $(BINDIR)
	install -d $(DATADIR)
	install -m 755 gallery_generator.sh $(BINDIR)/gallery_generator
	@for f in $(ASSETS); do \
		install -m 644 $$f $(DATADIR)/$$f; \
	done
	@echo ""
	@echo "Installed:"
	@echo "  $(BINDIR)/gallery_generator"
	@echo "  $(DATADIR)/ (assets)"
	@echo ""
	@echo "Run 'gallery_generator --help' to get started."
	@if [ ! -f $(ENV_FILE) ]; then \
		echo ""; \
		echo "  Tip: run 'make setup' to configure your environment."; \
	fi

uninstall:
	@echo "Uninstalling gallery_generator..."
	rm -f $(BINDIR)/gallery_generator
	rm -rf $(DATADIR)
	@echo "Done."

deps:
	@echo "Checking dependencies..."
	@echo ""
	@missing=0; \
	if command -v magick >/dev/null 2>&1 || command -v convert >/dev/null 2>&1; then \
		echo "  [ok] ImageMagick"; \
	else \
		echo "  [MISSING] ImageMagick"; \
		missing=1; \
	fi; \
	if command -v rsync >/dev/null 2>&1; then \
		echo "  [ok] rsync"; \
	else \
		echo "  [MISSING] rsync"; \
		missing=1; \
	fi; \
	if command -v htpasswd >/dev/null 2>&1; then \
		echo "  [ok] htpasswd"; \
	else \
		echo "  [MISSING] htpasswd"; \
		missing=1; \
	fi; \
	if command -v ssh >/dev/null 2>&1; then \
		echo "  [ok] ssh"; \
	else \
		echo "  [MISSING] ssh"; \
		missing=1; \
	fi; \
	echo ""; \
	if [ $$missing -eq 1 ]; then \
		echo "Install missing dependencies:"; \
		echo "  macOS:  brew install imagemagick rsync httpd"; \
		echo "  Ubuntu: sudo apt install imagemagick rsync apache2-utils openssh-client"; \
		exit 1; \
	else \
		echo "All dependencies are installed."; \
	fi

setup:
	@echo "=== Gallery Generator Setup ==="
	@echo ""
	@echo "This will create $(ENV_FILE)"
	@echo "with the settings needed to deploy galleries."
	@echo ""
	@if [ -f $(ENV_FILE) ]; then \
		echo "  WARNING: $(ENV_FILE) already exists."; \
		printf "  Overwrite? [y/N] "; \
		read ans; \
		case "$$ans" in [yY]*) ;; *) echo "Aborted."; exit 1;; esac; \
	fi
	@echo ""
	@echo "-- Required settings --"
	@echo ""
	@echo "SSH username for your remote host."
	@echo "  This is the user you SSH in as (e.g. deploy, myuser, dh_abc123)."
	@printf "  GALLERY_SSH_USER: "; \
	read ssh_user; \
	if [ -z "$$ssh_user" ]; then echo "Error: SSH user is required."; exit 1; fi; \
	echo ""; \
	echo "Domain name of the server where galleries will be hosted."; \
	echo "  e.g. photos.example.com"; \
	printf "  GALLERY_REMOTE_DOMAIN: "; \
	read domain; \
	if [ -z "$$domain" ]; then echo "Error: Domain is required."; exit 1; fi; \
	echo ""; \
	echo "-- Optional settings (press Enter to skip) --"; \
	echo ""; \
	echo "Base path on the remote server where gallery folders are created."; \
	echo "  Default: /home/$$ssh_user/$$domain"; \
	printf "  GALLERY_REMOTE_BASE_PATH: "; \
	read base_path; \
	echo ""; \
	echo "URL for a tip/support button shown on each gallery."; \
	echo "  e.g. https://account.venmo.com/u/yourname, https://ko-fi.com/yourname"; \
	printf "  GALLERY_TIP_URL: "; \
	read tip_url; \
	echo ""; \
	echo "# Gallery Generator configuration" > $(ENV_FILE); \
	echo "# Generated by 'make setup' on $$(date +%Y-%m-%d)" >> $(ENV_FILE); \
	echo "" >> $(ENV_FILE); \
	echo "# Required" >> $(ENV_FILE); \
	echo "GALLERY_SSH_USER=$$ssh_user" >> $(ENV_FILE); \
	echo "GALLERY_REMOTE_DOMAIN=$$domain" >> $(ENV_FILE); \
	if [ -n "$$base_path" ]; then \
		echo "" >> $(ENV_FILE); \
		echo "GALLERY_REMOTE_BASE_PATH=$$base_path" >> $(ENV_FILE); \
	fi; \
	if [ -n "$$tip_url" ]; then \
		echo "" >> $(ENV_FILE); \
		echo "GALLERY_TIP_URL=$$tip_url" >> $(ENV_FILE); \
	fi; \
	echo ""; \
	echo "Saved to $(ENV_FILE):"; \
	echo ""; \
	cat $(ENV_FILE); \
	echo ""; \
	echo "You can edit this file anytime: $(ENV_FILE)"; \
	echo "Test your SSH connection with: ssh $$ssh_user@$$domain exit"
